### Código feito por Rafael da Silva Fernandes - DRE: 117196229

## Importando bibliotecas

In [1]:
import numpy as np

## Variáveis globais

In [2]:
pagerank_inicial = np.array([1/4, 1/4, 1/4, 1/4])

pagerank_simplificado = np.array([
    [0, 0, 1, 0],
    [1/2, 0, 0, 0],
    [1/2, 1, 0, 1],
    [0, 0, 0, 0]
])

## Funções

### Pagerank

In [3]:
def pagerank(pagerank_simplificado, beta = 0.8):
    
    T = pagerank_simplificado.shape[0] 
    
    return ((1-beta)/ T) + (beta * pagerank_simplificado)

#### Teste função

In [4]:
print(pagerank(pagerank_simplificado)[0][0])
print(pagerank(pagerank(pagerank_simplificado)))

pagerank_simplificado.shape

0.04999999999999999
[[0.09 0.09 0.73 0.09]
 [0.41 0.09 0.09 0.09]
 [0.41 0.73 0.09 0.73]
 [0.09 0.09 0.09 0.09]]


(4, 4)

In [5]:
def pagerank_iteracao(pagerank_simplificado):
    
    threshold = 0.0001
    n_iteracoes = 0
    
    while True:
        
        for linha in range(pagerank_simplificado.shape[0]):
            for coluna in range(pagerank_simplificado.shape[1]):

                pagerank_resultado = pagerank(pagerank_simplificado)
                diferenca = pagerank_resultado[linha][coluna] - pagerank_simplificado[linha][coluna]
                
                if diferenca < threshold:
                    print("Número de iterações = ", n_iteracoes)
                    
                    pagerank_final = pagerank_resultado.sum(axis = 1)
                    print("Page rank = ", pagerank_final)
                    print("Rankeamento = ", np.argsort(pagerank_final)[::-1])
                    
                    return
                
                pagerank_simplificado = pagerank_resultado
                n_iteracoes += 1

#### Teste função

In [6]:
pagerank_iteracao(pagerank_simplificado)

Número de iterações =  2
Page rank =  [1.    0.744 1.768 0.488]
Rankeamento =  [2 0 1 3]
